services:
  # PostgreSQL Test Database
  postgres-test:
    image: postgres:15-alpine
    container_name: landly-postgres-test
    environment:
      POSTGRES_USER: landly
      POSTGRES_PASSWORD: landly
      POSTGRES_DB: landly_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U landly"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  # Redis Test Cache
  redis-test:
    image: redis:7-alpine
    container_name: landly-redis-test
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /data

  # MinIO Test Storage
  minio-test:
    image: minio/minio:latest
    container_name: landly-minio-test
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"
      - "9003:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /data

