name: E2E and Integration Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: landly
          POSTGRES_PASSWORD: landly
          POSTGRES_DB: landly_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        working-directory: apps/backend
        run: go mod download

      - name: Run integration tests
        working-directory: apps/backend
        env:
          TEST_POSTGRES_DSN: postgres://landly:landly@localhost:5433/landly_test?sslmode=disable
          TEST_REDIS_ADDR: localhost:6380
        run: go test -v -tags=integration ./...

